# Generated by Django 4.2.16 on 2024-09-18 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('total_price_excl_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_price_incl_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price_excl_tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('applicable_tax', models.DecimalField(decimal_places=2, max_digits=5)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.order')),
            ],
        ),
    ]
