# Generated by Django 4.2.16 on 2024-09-18 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price_excl_tax',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_price_incl_tax',
        ),
    ]
