# Generated by Django 4.2.16 on 2024-09-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_product_applicable_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='reference',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
